# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3676cb306cdddb51c677f7d7ef4a4f2a8f58be254a17ebae722cadf99cbfb1c2b653903df2d5c93b5ac911a820bfa830288953da40c602ff937512b595fc698c

test:
  secret_key_base: b469ceceb426ff0a0beafbc2fc209874db9f0dece2b3181bff2e7def1b999ea5a3f729ab9f2dff2b298344b61c295fc5fadb20eb6e6b5eef1fb4a2af3d67f60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
